name: Create report
on: [push]
jobs:
  phrase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: Test Reporter
        uses: dorny/test-reporter@v1.9.1
        with:
          name: Phrase check
          path: phrase-report.xml
          reporter: java-junit
