name: Development workflow
on:
  pull_request:
    branches:
      - gha-devx
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello step
        shell: bash
        run: |
          echo "A message just for me"
